# This workflow will upload a Python Package when a release is created

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/android-sms-gateway
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv

      - name: Install dependencies
        run: |
          pipenv install --deploy --dev

      - name: Build package
        run: |
          sed -i 's|VERSION = ".*"|VERSION = "'${GITHUB_REF_NAME:1}'"|g' ./android_sms_gateway/constants.py
          pipenv run python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
